version: '3.4'
services:
  cache:
    container_name: hive_cache
    image: redis/redis-stack:latest
    volumes:
      - cache:/data
    ports:
      - '6379:6379'
      - '13333:8001'
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASS:-eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81} --save 20 1 --loglevel warning"
    networks:
      - api
    restart: always
  db:
    container_name: hive_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hive_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-358227}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - api
    restart: unless-stopped
  web:
    container_name: hive_web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT:-8550}:${WEB_PORT:-8550}
    environment:
        WEB_PORT: ${WEB_PORT:-8550}
    restart: always
    networks:
      - api
  api:
    container_name: hive_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT:-8080}:${API_PORT:-8080}
    environment:
      API_PORT: ${API_PORT:-8080}
      API_HOST: ${API_HOST:-localhost}
    networks:
      - api
    depends_on:
      - cache
    restart: on-failure
networks:
  api:
    driver: bridge
volumes:
  cache:
  postgres: