on:
  push:
    branches:
      - main
      - devops
      - develop # TODO: Remove this line when devops branch is created
jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2